name: QuiteUsefulCommands
version: '${project.version}'
main: io.github.mightycoderx.quiteusefulcommands.QuiteUsefulCommands
api-version: 1.18
authors: [ MightyCoderX ]
description: A bunch of useful commands
commands:
  quiteusefulcommands:
    description: 'The main command of the plugin'
    usage: '/<command> [help | reload]'
    aliases: ['quc']
    permission: 'quiteusefulcommands.main'
  
  heal:
    description: 'Heal yourself or another player'
    usage: '/<command> [<player>]'
    permission: 'quiteusefulcommands.heal'
  
  feed:
    description: 'Feed yourself or another player'
    usage: '/<command> [<player>]'
    permission: 'quiteusefulcommands.feed'
  
  gm:
    description: 'Update your game mode'
    usage: '/<command> [<player>]'
    aliases: ['gms', 'gmc', 'gma', 'gmsp']
    permission: 'quiteusefulcommands.gamemode'
    
  fly:
    description: 'Toggles fly for you or another player'
    usage: '/<command> [<player>]'
    permission: 'quiteusefulcommands.fly'
    
  sudo:
    description: 'Makes <player> execute <command>'
    usage: '/<command> <player> <command>'
    permission: 'quiteusefulcommands.sudo'

  enderchest:
    description: 'Open your enderchest or that of <player>'
    usage: '/<command> [<player>]'
    aliases: ['echest', 'ender']
    permission: 'quiteusefulcommands.enderchest'
  
  workbench:
    description: 'Open a workbench'
    usage: '/<command>'
    aliases: [
        'craft', 'wbench',
#        'enchanting', 'etable',
#        'loom',
#        'cartography', 'cartographytable', 'carttable',
#        'stonecutter',
#        'grindstone',
#        'smithingtable', 'smithtable',
#        'anvil', 'rename'
    ]
    permission: 'quiteusefulcommands.crafting'
    
  invsee:
    description: 'Open your inventory or that of <player>'
    usage: '/<command> [<player>]'
    permission: 'quiteusefulcommands.invsee'
    
  ride:
    description: 'Makes you ride <player>'
    usage: '/<command> <player>'
    aliases: [ 'mount', 'rideplayer', 'mountplayer']
    permission: 'quiteusefulcommands.ride'
    
  spawnmob:
    description: 'Spawns a mob or multiple'
    usage: '/<command> <mob> [<count>]'
    aliases: ['spawnentity', 'mob']
    permission: 'quiteusefulcommands.spawnmob'
    
  custommap:
    description: 'Gives you a custom map with the color or image you specified'
    usage: '/<command> <color <color> | image <url> [<startPosX> <startPosY>] [<scaleDown>] | big_image <url>'
    permission: 'quiteusefulcommands.custommap'
    
  freeze:
    description: 'Toggles freeze for <player>'
    usage: '/<command> <player>'
    permission: 'quiteusefulcommands.freeze'
    
  godmode:
    description: 'Toggles godmode for you or <player>'
    usage: '/<command> [<player>]'
    permission: 'quiteusefulcommands.godmode'
    
  speed:
    description: "Set your or <player>'s fly/walk speed to <speed>"
    usage: '/<command> <fly | walk> <speed> [player]'
    aliases: ['flyspeed', 'walkspeed']
    permission: 'quiteusefulcommands.speed'
    
  powertool:
    description: 'Bind a command to the item in your hand'
    usage: '/<command> <add [c:]<command> | remove | clear [player]>'
    aliases: ['pt']
    permission: 'quiteusefulcommands.powertool'